.PHONY: clear

clear:
	@find . -maxdepth 1 -type f \
		! -name "*.txt" \
		! -name "*.bib" \
		! -name "*.pdf" \
		! -name "*.zip" \
		! -name "*.png" \
		! -name "*.tex" \
		! -name "*.c" \
		! -name "*.svg" \
		! -name "*.docs" \
		! -name "makefile" \
		-exec rm -f {} \;
